language: r
r: 3.3.3
warnings_are_errors: true
sudo: required
cache: packages

r_github_packages:
  - jimhester/covr

#r_packages:
#  - covr

r_binary_packages:
  - gsl

env:
  - NOT_CRAN=true

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
