language: r
r: release
warnings_are_errors: true
sudo: required
cache: packages

before_install:
  - ./travis-tool.sh aptget_install libgsl0-dev

r_packages:
  - covr

env:
  - NOT_CRAN=true

after_success:
  - Rscript -e 'library(covr); codecov()'
