language: r
r: release
warnings_are_errors: true
sudo: required
cache: packages

r_packages:
  - covr

r_binary_packages:
  - gsl

env:
  - NOT_CRAN=true

after_success:
  - travis_wait Rscript -e 'library(covr); codecov()'
