language: r
r: release
warnings_are_errors: true
sudo: false
cache: packages

r_packages:
  - lme4
  - xml2

r_github_packages:
  - jimhester/covr

env:
  - NOT_CRAN=true

after_success:
  - Rscript -e 'library(covr); codecov()'
