language: r
r: release
warnings_are_errors: true
sudo: required
cache: packages
dist: trusty
r_check_args: --no-tests --as-cran --no-manual

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh aptget_install libgsl0-dev

#r_github_packages:
#  - jimhester/covr

r_packages:
  - R.rsp
  - covr

r_binary_packages:
  - gsl

env:
  - NOT_CRAN=true

after_success:
  - travis_wait 20 Rscript -e 'covr::codecov()'
